export const mockBooks = [
  {
    id: 1,
    cover_img: "https://covers.openlibrary.org/b/id/10522956-L.jpg",
    title: "Zero to One",
    author: "Peter Thiel",
    description: "Notes on startups, innovation, and building the future.",
    rating: 4.5,
    genre: "Business",
  },
  {
    id: 2,
    cover_img: "https://covers.openlibrary.org/b/id/10815995-L.jpg",
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    description: "A classic guide to financial literacy and wealth building.",
    rating: 4.7,
    genre: "Finance",
  },
  {
    id: 3,
    cover_img: "https://covers.openlibrary.org/b/id/10290268-L.jpg",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    description: "A counterintuitive approach to living a good life.",
    rating: 4.4,
    genre: "Self-help",
  },
  {
    id: 4,
    cover_img: "https://covers.openlibrary.org/b/id/11133325-L.jpg",
    title: "Ikigai",
    author: "Héctor García & Francesc Miralles",
    description: "The Japanese secret to a long and happy life.",
    rating: 4.6,
    genre: "Philosophy",
  },
  {
    id: 5,
    cover_img: "https://covers.openlibrary.org/b/id/11133985-L.jpg",
    title: "Can't Hurt Me",
    author: "David Goggins",
    description: "Master your mind and defy the odds.",
    rating: 4.8,
    genre: "Biography",
  },
  {
    id: 6,
    cover_img: "https://covers.openlibrary.org/b/id/10840733-L.jpg",
    title: "The Lean Startup",
    author: "Eric Ries",
    description: "How today’s entrepreneurs use continuous innovation.",
    rating: 4.3,
    genre: "Business",
  },
  {
    id: 7,
    cover_img: "https://covers.openlibrary.org/b/id/10476941-L.jpg",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    description: "The official biography of Apple co-founder Steve Jobs.",
    rating: 4.7,
    genre: "Biography",
  },
  {
    id: 8,
    cover_img: "https://covers.openlibrary.org/b/id/11154025-L.jpg",
    title: "Start With Why",
    author: "Simon Sinek",
    description: "How great leaders inspire everyone to take action.",
    rating: 4.6,
    genre: "Leadership",
  },
  {
    id: 9,
    cover_img: "https://covers.openlibrary.org/b/id/10929667-L.jpg",
    title: "Mindset",
    author: "Carol S. Dweck",
    description: "The new psychology of success and personal growth.",
    rating: 4.5,
    genre: "Psychology",
  },
  {
    id: 10,
    cover_img: "https://covers.openlibrary.org/b/id/11087920-L.jpg",
    title: "The 5 AM Club",
    author: "Robin Sharma",
    description: "Own your morning, elevate your life.",
    rating: 4.3,
    genre: "Motivation",
  },
  {
    id: 11,
    cover_img: "https://covers.openlibrary.org/b/id/10833858-L.jpg",
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    description: "Timeless principles for communication and leadership.",
    rating: 4.8,
    genre: "Self-help",
  },
  {
    id: 12,
    cover_img: "https://covers.openlibrary.org/b/id/10527642-L.jpg",
    title: "Make Time",
    author: "Jake Knapp & John Zeratsky",
    description: "How to focus on what matters every day.",
    rating: 4.4,
    genre: "Productivity",
  },
  {
    id: 13,
    cover_img: "https://covers.openlibrary.org/b/id/11027742-L.jpg",
    title: "Factfulness",
    author: "Hans Rosling",
    description: "Ten reasons we're wrong about the world – and why things are better than you think.",
    rating: 4.7,
    genre: "Non-Fiction",
  },
  {
    id: 14,
    cover_img: "https://covers.openlibrary.org/b/id/11106189-L.jpg",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    description: "Timeless lessons on wealth, greed, and happiness.",
    rating: 4.8,
    genre: "Finance",
  },
  {
    id: 15,
    cover_img: "https://covers.openlibrary.org/b/id/10689371-L.jpg",
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    description: "A psychiatrist’s memoir of life in Nazi death camps and lessons for spiritual survival.",
    rating: 4.9,
    genre: "Philosophy",
  },
  {
    id: 16,
    cover_img: "https://covers.openlibrary.org/b/id/10734754-L.jpg",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    description: "A guide to spiritual enlightenment and presence.",
    rating: 4.4,
    genre: "Spirituality",
  },
  {
    id: 17,
    cover_img: "https://covers.openlibrary.org/b/id/10888042-L.jpg",
    title: "Drive",
    author: "Daniel H. Pink",
    description: "The surprising truth about what motivates us.",
    rating: 4.2,
    genre: "Psychology",
  },
  {
    id: 18,
    cover_img: "https://covers.openlibrary.org/b/id/11005098-L.jpg",
    title: "Grit",
    author: "Angela Duckworth",
    description: "The power of passion and perseverance.",
    rating: 4.5,
    genre: "Motivational",
  },
];
